### ISSUE TITLE
Create ClusterRole with non-existent Service Account

### ISSUE THREAD

**Issue by vinicius-colutti** [aws/eks-news#114]
**Describe the bug**
Was creating a ClusterRole and ClusterRoleBinding in my EKS Cluster, using CloudFormation. So, due to lack of attention, I informed a non-existent ServiceAccount, for example:

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-custom-role
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - endpoints
      - pods
      - nodes
      - services
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-custom-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-custom-role
subjects:
  - kind: ServiceAccount
    name: invalidNameHere
    namespace: mycustomnamespace
```

But, these resources were created successfully without any warnings or errors.

So I thought... is this behavior correct? Will create unnecesary resourcers with non-existent attributes.

I noticed this issue, when I tested my application and got 403 Forbidden from k8s, then, I saw the ClusterRole associated with a non-existent ServiceAccount, but, created.

Is there any reason why he allowed the creation?

**Platform/OS/Hardware/Device**
EKS, Linux

**To Reproduce (observed behavior)**
Try to create a ClusterRole with non-existent ServiceAccount, using infraascode

**Expected behavior**
Do not allow the creation of the resource, because if the ServiceAccount does not exist, this resource will be unnecessary and confusing.

**Additional context**
If there are reasons for this behavior, please, explain for me, thank you very much!
